version: '2'
services:
    leboncoindetailscrapper-app:
        image: leboncoindetailscrapper
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://leboncoindetailscrapper-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=leboncoinDetailScrapper
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    leboncoindetailscrapper-mongodb:
        extends:
            file: mongodb.yml
            service: leboncoindetailscrapper-mongodb
